[project]
name = "analytics-serlo-hochschulmathematik"
version = "0.1.0"
description = "Analytics of page views for the project â€Serlo Hochschulmathematikâ€œ"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
